name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxrandr-dev libx11-dev libxcursor-dev libxinerama-dev libxi-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.4' # 使用的 Go 版本，可以根据需要调整

    - name: Compile code
      run: go build -v main.go
