name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Docker
      run: |
        docker build -t my-golang-app .
        docker run my-golang-app

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: ./bin
